version: "3.8"

services:
  share:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - SECRET_TOKEN=value
      - MINIO_ENDPOINT=minio
    depends_on:
      - minio
    networks:
      - default
      - npm

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    volumes:
      - ./data:/data:rw,z
    environment:
      - MINIO_ROOT_USER=miniousername
      - MINIO_ROOT_PASSWORD=miniopassword
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - default

networks:
  default:
  npm:
    external: true
    name: npm_default
